FROM amazonlinux:2027
ENV HOME=/
RUN dnf update -y
RUN dnf install -y rpmdevtools dnf-plugins-core

RUN rpmdev-setuptree
RUN echo '%dist   .amzn2027' >> /.rpmmacros
COPY ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN dnf builddep -y /rpmbuild/SPECS/mysql.spec
RUN spectool -g -R /rpmbuild/SPECS/mysql.spec && \
  rpmbuild -ba /rpmbuild/SPECS/mysql.spec && \
  tar -czf /tmp/mysql.tar.gz -C /rpmbuild RPMS SRPMS && \
  rm -rf /rpmbuild
CMD ["/bin/true"]
